spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://sucifitz.top:3306/eshop
    username: eshop
    password: eshop
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis配置
  redis:
    cluster:
      # 集群节点
      nodes: sucifitz.top:8010, sucifitz.top:8011, sucifitz.top:8012
    # 密码
    password: